name: aws_lambda_dart_runtime
version: 1.1.0
description: |-
  A powerful runtime to build Lambda functions in Dart with native AWS events.
homepage: https://github.com/awslabs/aws-lambda-dart-runtime
documentation: https://awslabs.github.io/aws-lambda-dart-runtime/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  json_annotation: ^4.8.1
  meta: ^1.11.0
  http: ^1.1.0

dev_dependencies:
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  test: ^1.24.8
  mockito: ^5.4.2